### ISSUE TITLE
Really...

### ISSUE THREAD

**Issue by wendellmeset** [NotAiTristanAlt/Tulipcraft-Sucks#1]

**Comment by NotAiTristanAlt** [comment]
oh look, its the shitty dev, you here to fuck yourself, I just noticed you banned me again, so im angry, i hope your fucking shit server died, IDIOT, oh, also, i have a alt on your discord server so im spying on you guys, by the way, I was the one who spammed your money finder webhook/websocket, it was ezzzz shit

**Comment by NotAiTristanAlt** [comment]
Jamie, if your reading this, i can see every message in your dms, i managed to get a bug on your pc lol, have fun finding it idiot

**Comment by Errorcrafter** [comment]
last i checked, 9 year-olds aren't allowed on github according to the ToS
